### ISSUE TITLE
How can I use Insight with BitcoinXT? 

### ISSUE THREAD

**Issue by zekylaf** [bitpay/insight#657]
Hi, I am using Bitcoin Core with Insight, but I want to install Bitcoin XT and use Insight with this. What I have to do to achieve that?

Thanks

**Comment by SoreGums** [comment]
It's the same...
Only reason I found Insight is because of XT and this discussion about big blocks.
Messed up and had to start again, took about 18hrs to fully sync bitcoin blockchain - just kicked off Insight 1min ago.

so just stop insight.
and spin up bitcoind (xt) - should use the same config folder/database and everything and then start insight up again - should be all sweet.

**Comment by SoreGums** [comment]
and just finished syncing - took: 7 days & 2 hrs

**Comment by braydonf** [comment]
There is a forum at https://labs.bitpay.com/c/bitcore/insight for support related questions.
