### ISSUE TITLE
Sent bit coin 3 days ago still shows uncomfirmed please check on this .18fTEeZooPhXthJbQxqucgV8agf4qTv7aE

### ISSUE THREAD

**Issue by scwei1** [bitpay/insight#904]

**Comment by teran-mckinney** [comment]
I don't see any pending balance here: https://insight.bitpay.com/address/18fTEeZooPhXthJbQxqucgV8agf4qTv7aE

Did you send the transaction with an adequate fee per byte?

Also note that these issues should be for Insight, and not just general Bitcoin questions.

**Comment by teran-mckinney** [comment]
You're welcome. I can't see 2e3a8443f96ddbdc55ac5d6787530ebeb4b76271cfd05adefe0f0bd990bda70 on Insight, Blockchain.info, or Bitaps.

Must be an invalid transaction. I don't think it's a fee problem since it's not showing up at all. Should at least make it to mempool.

No experience with the Trezor. Not sure what to suggest from here.

**Comment by matiu** [comment]
Since the TX is not on the blockchain, you should check with the sending wallet.
